import type { CommandCenterData } from "./command-center.types";

export const commandCenterData: CommandCenterData = {
  user: {
    firstName: "علي",
    role: "مدير المشتريات",
  },

  date: "الثلاثاء، 14 يوليو 2026",

  hero: {
    eyebrow: "مركز القيادة الذكي",
    title: "صباح الخير، علي",
    description:
      "إليك نظرة سريعة على أعمال اليوم. لديك 12 مهمة تحتاج إلى المتابعة، منها 3 إجراءات ذات أولوية عالية.",

    progress: {
      percentage: 68,
      completed: 12,
      total: 18,
    },

    alerts: [
      {
        id: "approvals",
        title: "اعتمادات معلقة",
        value: 3,
        description: "تحتاج إلى قرارك",
        tone: "red",
        icon: "✓",
      },
      {
        id: "closing",
        title: "منافسات تغلق اليوم",
        value: 2,
        description: "خلال 24 ساعة",
        tone: "orange",
        icon: "⌛",
      },
      {
        id: "contracts",
        title: "عقود للمراجعة",
        value: 4,
        description: "بانتظار الإجراء",
        tone: "blue",
        icon: "▤",
      },
      {
        id: "suppliers",
        title: "موردون جدد",
        value: 3,
        description: "مكتملو التسجيل",
        tone: "green",
        icon: "◎",
      },
    ],
  },

  kpis: [
    {
      id: "contract-value",
      title: "قيمة العقود النشطة",
      value: "18.4M",
      unit: "ريال سعودي",
      change: "15%",
      trend: "up",
      tone: "blue",
      icon: "◇",
      chart: [18, 22, 20, 28, 25, 34, 31, 43],
    },
    {
      id: "win-rate",
      title: "نسبة الفوز",
      value: "32%",
      change: "0.5%",
      trend: "up",
      tone: "purple",
      icon: "◉",
      chart: [25, 27, 26, 30, 29, 33, 31, 36],
    },
    {
      id: "active-contracts",
      title: "عدد العقود النشطة",
      value: "24",
      change: "2%",
      trend: "down",
      tone: "purple",
      icon: "▤",
      chart: [12, 14, 13, 18, 17, 22, 20, 24],
    },
    {
      id: "suppliers",
      title: "الموردون المعتمدون",
      value: "156",
      change: "4.5%",
      trend: "up",
      tone: "green",
      icon: "◎",
      chart: [90, 105, 98, 119, 112, 134, 128, 156],
    },
    {
      id: "monthly-procurement",
      title: "مشتريات هذا الشهر",
      value: "7.8M",
      unit: "ريال سعودي",
      change: "9%",
      trend: "up",
      tone: "cyan",
      icon: "↗",
      chart: [3, 4, 3.8, 5.2, 4.9, 6.4, 6.1, 7.8],
    },
    {
      id: "projects",
      title: "المشاريع النشطة",
      value: "18",
      change: "3",
      trend: "up",
      tone: "purple",
      icon: "◇",
      chart: [8, 10, 9, 12, 11, 14, 13, 18],
    },
  ],

  intelligence: {
    winProbability: 92,
    change: "18%",
    insights: [
      {
        id: "opportunity-match",
        title: "فرصة مناسبة لنشاط الشركة",
        description:
          "توجد 3 منافسات جديدة تتوافق مع تصنيف الشركة وخبراتها السابقة.",
        actionLabel: "عرض الفرص",
        tone: "blue",
        icon: "◇",
      },
      {
        id: "contract-review",
        title: "عقد يحتاج إلى مراجعة",
        description:
          "عقد مشروع مجمع الملك عبدالله يحتوي على بند يحتاج إلى الانتباه.",
        actionLabel: "مراجعة العقد",
        tone: "green",
        icon: "▤",
      },
      {
        id: "possible-delay",
        title: "احتمال تأخر مشروع",
        description:
          "يتوقع النظام تأخرًا محتملًا في مشروعين بناءً على تقدم الأعمال.",
        actionLabel: "عرض التفاصيل",
        tone: "purple",
        icon: "◷",
      },
    ],
  },

  quickActions: {
    actions: [
      {
        id: "new-rfq",
        title: "إنشاء منافسة",
        description: "ابدأ طلب عرض سعر جديد",
        href: "/platform/opportunities/new",
        tone: "blue",
        icon: "＋",
      },
      {
        id: "new-contract",
        title: "إنشاء عقد",
        description: "إضافة عقد جديد",
        href: "/platform/contracts/new",
        tone: "green",
        icon: "▤",
      },
      {
        id: "new-supplier",
        title: "إضافة مورد",
        description: "تسجيل شريك أعمال",
        href: "/platform/partners/new",
        tone: "purple",
        icon: "◎",
      },
      {
        id: "new-project",
        title: "إنشاء مشروع",
        description: "فتح مشروع جديد",
        href: "/platform/projects/new",
        tone: "orange",
        icon: "◇",
      },
      {
        id: "upload-document",
        title: "رفع مستند",
        description: "إضافة ملف إلى المركز",
        href: "/platform/documents",
        tone: "cyan",
        icon: "⇧",
      },
      {
        id: "new-approval",
        title: "طلب موافقة",
        description: "إرسال طلب اعتماد",
        href: "/platform/approvals/new",
        tone: "green",
        icon: "✓",
      },
    ],
  },
  operations: {
    pipeline: [
      {
        id: "new",
        title: "طلبات جديدة",
        value: 18,
        description: "بانتظار الفرز",
        tone: "blue",
      },
      {
        id: "published",
        title: "منشورة",
        value: 12,
        description: "تستقبل عروضًا",
        tone: "cyan",
      },
      {
        id: "technical",
        title: "تقييم فني",
        value: 8,
        description: "قيد المراجعة",
        tone: "purple",
      },
      {
        id: "commercial",
        title: "تقييم مالي",
        value: 6,
        description: "تحليل الأسعار",
        tone: "orange",
      },
      {
        id: "awarded",
        title: "تمت الترسية",
        value: 3,
        description: "خلال هذا الشهر",
        tone: "green",
      },
    ],

    tasks: [
      {
        id: "task-1",
        title: "اعتماد التقييم المالي لمنافسة التوريد",
        context: "RFQ-2026-014",
        dueLabel: "خلال ساعتين",
        priority: "high",
        completed: false,
      },
      {
        id: "task-2",
        title: "مراجعة المسودة النهائية لعقد الصيانة",
        context: "CON-2026-031",
        dueLabel: "اليوم، 2:30 م",
        priority: "high",
        completed: false,
      },
      {
        id: "task-3",
        title: "الرد على استفسارات الموردين",
        context: "منافسة مشروع التشجير",
        dueLabel: "غدًا",
        priority: "medium",
        completed: false,
      },
      {
        id: "task-4",
        title: "تحديث بيانات مشروع توسعة المستودع",
        context: "PRJ-2026-008",
        dueLabel: "هذا الأسبوع",
        priority: "low",
        completed: true,
      },
    ],

    opportunities: [
      {
        id: "opp-1",
        reference: "RFQ-2026-014",
        title: "توريد وتركيب أنظمة المراقبة",
        organization: "شركة البناء الحديثة",
        closingLabel: "يغلق خلال يومين",
        progress: 78,
        status: "closing",
        value: "4.8 م ر.س",
      },
      {
        id: "opp-2",
        reference: "RFP-2026-009",
        title: "أعمال تطوير البنية التحتية",
        organization: "شركة الخليج للمقاولات",
        closingLabel: "يغلق خلال 6 أيام",
        progress: 52,
        status: "published",
        value: "12.5 م ر.س",
      },
      {
        id: "opp-3",
        reference: "RFQ-2026-011",
        title: "خدمات التشغيل والصيانة السنوية",
        organization: "مجموعة أفق",
        closingLabel: "قيد التقييم",
        progress: 86,
        status: "evaluation",
        value: "7.2 م ر.س",
      },
      {
        id: "opp-4",
        reference: "TEN-2026-004",
        title: "إنشاء مستودعات ومرافق لوجستية",
        organization: "شركة المدى",
        closingLabel: "مسودة",
        progress: 31,
        status: "draft",
        value: "18.9 م ر.س",
      },
    ],

    events: [
      {
        id: "event-1",
        day: "15",
        month: "يوليو",
        title: "إغلاق منافسة أنظمة المراقبة",
        description: "RFQ-2026-014",
        time: "4:00 م",
        tone: "red",
      },
      {
        id: "event-2",
        day: "17",
        month: "يوليو",
        title: "اجتماع لجنة التقييم",
        description: "قاعة الاجتماعات الرئيسية",
        time: "10:30 ص",
        tone: "purple",
      },
      {
        id: "event-3",
        day: "20",
        month: "يوليو",
        title: "تجديد عقد الصيانة",
        description: "CON-2025-087",
        time: "طوال اليوم",
        tone: "orange",
      },
      {
        id: "event-4",
        day: "22",
        month: "يوليو",
        title: "زيارة موقع المشروع",
        description: "مشروع توسعة المستودع",
        time: "8:00 ص",
        tone: "green",
      },
    ],
  },

  performance: {
    periodLabel: "آخر 6 أشهر",
    points: [
      { label: "فبراير", contracts: 3.8, procurement: 2.4 },
      { label: "مارس", contracts: 5.1, procurement: 3.6 },
      { label: "أبريل", contracts: 4.7, procurement: 4.2 },
      { label: "مايو", contracts: 7.2, procurement: 5.1 },
      { label: "يونيو", contracts: 6.5, procurement: 6.3 },
      { label: "يوليو", contracts: 9.4, procurement: 7.8 },
    ],
    metrics: [
      {
        id: "contract-growth",
        label: "نمو قيمة العقود",
        value: "18.6%",
        change: "+4.2%",
        trend: "up",
        tone: "blue",
      },
      {
        id: "procurement-saving",
        label: "وفورات المشتريات",
        value: "2.4 م",
        change: "+11.8%",
        trend: "up",
        tone: "green",
      },
      {
        id: "cycle-time",
        label: "متوسط دورة الترسية",
        value: "21 يومًا",
        change: "-3 أيام",
        trend: "up",
        tone: "purple",
      },
    ],
  },

  activity: {
    items: [
      {
        id: "activity-1",
        title: "تم اعتماد التقييم المالي",
        description: "منافسة توريد أنظمة المراقبة",
        time: "منذ 18 دقيقة",
        actor: "علي محمد",
        icon: "✓",
        tone: "green",
      },
      {
        id: "activity-2",
        title: "تم رفع عرض فني جديد",
        description: "بواسطة شركة الخليج للمقاولات",
        time: "منذ 42 دقيقة",
        actor: "نظام الموردين",
        icon: "⇧",
        tone: "blue",
      },
      {
        id: "activity-3",
        title: "اكتشف OQOOD AI مخاطرة تعاقدية",
        description: "في عقد مشروع مجمع الملك عبدالله",
        time: "منذ ساعة",
        actor: "OQOOD Intelligence",
        icon: "✦",
        tone: "purple",
      },
      {
        id: "activity-4",
        title: "تم نشر منافسة جديدة",
        description: "أعمال تطوير البنية التحتية",
        time: "منذ ساعتين",
        actor: "إدارة المشتريات",
        icon: "◇",
        tone: "orange",
      },
      {
        id: "activity-5",
        title: "اقترب موعد انتهاء عقد",
        description: "عقد التشغيل والصيانة السنوي",
        time: "منذ 3 ساعات",
        actor: "نظام العقود",
        icon: "!",
        tone: "red",
      },
    ],
  },
};
